#!/bin/sh

if [ ! -e ~/bin ]; then
    mkdir ~/bin
fi

cp r.series.distributed ~/bin/r.series.distributed
cp r.sun.distributed ~/bin/r.sun.distributed
cp rmean.sh ~/bin/rmean.sh
cp rsun.sh ~/bin/rsun.sh


