.TH r.eemt.distributed 1 "18 May 2015" "Version 0.0.1" "Sol Manual"

.SH NAME
r.eemt.distributed \- Distributed Effective Energy to Mass Transfer Model Generator

.SH SYNOPSIS
.B r.eemt.distributed 
[DEM] [options]

.SH DESCRIPTION
.B r.eemt.distributed
creates EEMT models for the given DEM and date range.  It uses WorkQueue(CCTools) to distributed the create of Solar Insolation models across many nodes.

.SH OPTIONS
.B -s, --start-year
Specify start year for model generation (Default: 1980)

.B -e, --end-year
Specify end year for model generation (Default: 2012)

.B -n, --name
Specify WorkQueue project name (Default: [USER]_EEMT)

.B -p
Specify port for WorkQueue to run on (Default: 9125)
