.TH reemt.sh 1 "18 May 2015" "Version 0.0.1" "Sol Manual"

.SH NAME
reemt.sh \- Runs GRASS GIS to create Effective Energy to Mass Transfer Model

.SH SYNOPSIS
.B reemt.sh
[Directory] [Month] [Year] [DEM] [NA_DEM] [TMIN] [TMAX] [VP] [PRCP] [TWI] [TOTAL_SUN] [HOURS_SUN] [FLAT_SUN] [SLOPE] [ASPECT]

.SH DESCRIPTION
.B reemt.sh
creates EEMT models for the given month and year, based of the DEM and weather data provided


