.TH rsun.sh 1 "18 May 2015" "Version 0.0.1" "Sol Manual"

.SH NAME
.B rsun.sh \- Calculates Flat Solar Irradiation, Global Insolation, and Insolation Time for a given DEM and day

.SH SYNOPSIS
.B rsun.sh
[DEM] [options]

.SH DESCRIPTION
.B rsun.sh
creates various solar insolation models using GRASS GIS software.

.SH OPTIONS
.B -d, --day
Specify Day to create models for
